package com.hackathon.entity.enums;

public enum AuditAction {
    CREATE_EVENT,
    UPDATE_EVENT,
    DELETE_EVENT,
    CANCELLD_EVENT,
    CREATE_TEAM,
    UPDATE_ROUND,
    UPDATE_CRITERIA,
    UPDATE_TEAM,
    DELETE_TEAM,
    CREATE_CRITERIA,
    DELETE_CRITERIA,
    SUBMIT_PROJECT,
    LOGIN,
    LOGOUT,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    DISQUALIFY_TEAM,
    SAVE_DRAFT,
    PUBLISH_FINAL,
    APPROVE_RANKING,
    REJECT_RANKING,
    OPEN_APPEAL,
    //MENTOR
    SEND_MENTOR_REQUEST,
    MENTOR_ACCEPT_REQUEST,
    MENTOR_REJECT_REQUEST,
    SEND_APPEAL_REQUEST,
    REJECT_APPEAL_REQUEST,
    ACCEPT_APPEAL_REQUEST,
    REQUEST_RE_EVALUATION,

    SUBMIT_EVALUATION,
    UPDATE_EVALUATION,
    RE_SUBMIT_EVALUATION,

    REGISTER_EVENT
    ;

}
