package com.hackathon.entity.enums;

public enum NotificationType {
    TEAM_INVITATION,

    TEAM_REGISTRATION_APPROVED,
    TEAM_REGISTRATION_REJECTED,

    DISQUALIFY_TEAM,
    ASSIGNED_CATEGORY,

    CANCELLED_EVENT,

    LEADER_TRANSFER_REQUEST,
    SUBMISSION_REVIEW,

    RANKING_DRAFT,
    RANKING_OFFICIAL,
    SCORING_COMPLETED,
    SCORING_FAILED,
    RESULT_APPEAL,
    SUPPORT_TEAM
}
